"""cascade relations

Revision ID: 07ed58de9ddb
Revises: 30ebc0241cfd
Create Date: 2023-07-26 20:13:50.395573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07ed58de9ddb'
down_revision = '30ebc0241cfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_measurement', sa.Float(), nullable=True))

    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_unique_constraint('timestamp_on_channel_id_contstraint', ['timestamp', 'channel_id'])

    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.alter_column('installed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.alter_column('installed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_constraint('timestamp_on_channel_id_contstraint', type_='unique')

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_column('latest_measurement')

    # ### end Alembic commands ###
