"""init

Revision ID: 436d73d23db9
Revises: 
Create Date: 2023-07-19 13:40:53.867994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436d73d23db9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('contracted_power_kw', sa.Integer(), nullable=True),
    sa.Column('contracted_power_m3', sa.Integer(), nullable=True),
    sa.Column('contracted_power_l', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_installation_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_installation_owner_email'), ['owner_email'], unique=False)

    op.create_table('meter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ean', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean')
    )
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_installation_id'), ['installation_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['installation_id'], ['installation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_hashed_password'), ['hashed_password'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('qanteon_name', sa.String(), nullable=True),
    sa.Column('qanteon_id', sa.Integer(), nullable=True),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_meter_id'), ['meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_qanteon_id'), ['qanteon_id'], unique=False)

    op.create_table('measurement',
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('accumulated', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'channel_id'),
    sa.UniqueConstraint('timestamp', 'channel_id', name='one_timestamp_per_channel_id_contstraint')
    )
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurement_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_timestamp'))
        batch_op.drop_index(batch_op.f('ix_measurement_channel_id'))

    op.drop_table('measurement')
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_qanteon_id'))
        batch_op.drop_index(batch_op.f('ix_channel_name'))
        batch_op.drop_index(batch_op.f('ix_channel_meter_id'))
        batch_op.drop_index(batch_op.f('ix_channel_id'))

    op.drop_table('channel')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_hashed_password'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('meter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_installation_id'))
        batch_op.drop_index(batch_op.f('ix_meter_id'))

    op.drop_table('meter')
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_owner_email'))
        batch_op.drop_index(batch_op.f('ix_installation_name'))
        batch_op.drop_index(batch_op.f('ix_installation_id'))

    op.drop_table('installation')
    # ### end Alembic commands ###
