"""loosen channel restrcition

Revision ID: 569af5c47ae5
Revises: 07ed58de9ddb
Create Date: 2023-07-28 14:47:30.343002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569af5c47ae5'
down_revision = '07ed58de9ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.alter_column('latest_measurement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.alter_column('latest_measurement',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
